
  <form method="post" action="regmailer_hopu.asp">

  <table border=0 width="100%">
  <tr><td><center>
   <table border=0>
    <tr><td colspan=3 height="16">
       <center>
         <font color=brown size=+2>Kamp Ka Lewa Individual Registration Form</font><br><hr>
       </center>
   </td></tr>

    <tr>
      <td width="35%" align=right valign=top>First Name<sup>*</sup></td>
      <td width="5%"">&nbsp;&nbsp;</td> 
      <td width="60%"> <input name ="firstname" type="text" size="20">
    </td></tr>

    <tr><td align=right valign=top>Last Name<sup>*</sup></td>
      <td height="22"></td> 
      <td height="22"> <input name="lastname" type="text" size="20">
    </td></tr>

    <tr><td align=right valign=top>Sex<sup>*</sup></td> <td height="20"></td> 
      <td height="20">
         <input name="gender" type="radio" value="Male"> Male&nbsp;&nbsp;
         <input name="gender" type="radio" value="Female"> Female
    </td></tr>

    <tr><td align=right valign=top>Team<sup>*</sup></td>
      <td height="22"></td>
      <td height="22"> <input name="team" type="text" size="30">
        <br><br><font color=green>Individual sign-ups put Aloha Spirit as your team</font>
    </td></tr>

<!--
    <tr><td align=right valign=top>Team<sup>*</sup></td> <td></td> <td>
	<select name=team>
	 <option value="blank">
	 <option value="Aloha Spirit">Aloha Spirit
	 <option value="Claiaskawai'i">Claiaskawai'i     		
	 <option value="Classy">Classy	
	 <option value="Doh">Doh
	 <option value="Hana Hou">Hana Hou
	 <option value="Hucking Faoles">Hucking Faoles
	 <option value="Lava Flow">Lava Flow
	 <option value="Pirates">Pirates
	 <option value="Sippin' Sallies">Sippin' Sallies
	 <option value="Swingers and Dumpers">Swingers and Dumpers
	 <option value="Swing Of Fire">Swing Of Fire
	 <option value="Wheres My McDreamy">Wheres My McDreamy
	 <option value="GUEST">GUEST	
	 <option value="Hat Draw">Hat Draw
	</select>

        <br><br><font color=green>Individual sign-ups put Aloha Spirit as your team</font>
    </td></tr>
-->

    <tr><td colspan=3>&nbsp;</td></tr>
 
    <tr><td align=right valign=top>Email<sup>*</sup></td>
      <td height="22"></td> 
      <td height="22"> <input name="email" type="text" size="20">
    </td></tr>

    <tr><td align=right valign=top>Phone Number<sup>*</sup></td>
      <td height="22"></td> 
      <td height="22"> <input name="phone" type="text" size="20">
    </td></tr>

    <tr><td align=right valign=top>Age<sup>*</sup></td>
       <td height="20"></td> 
       <td height="20">
          <input name="age" type="radio" value="Over21"> Over 21&nbsp;&nbsp;
          <input name="age" type="radio" value="Under21"> Under 21
     </td></tr>

    <tr><td colspan=3>&nbsp;</td></tr>

    <tr><td align=right valign=top>Emergency Contact Name<sup>*</sup></td>
      <td height="32"></td> 
      <td height="32"> <input name="emergencyname" type="text" size="20">
    </td></tr>

    <tr><td align=right valign=top>Emergency Contact Phone<sup>*</sup></td> 
      <td height="32"></td> 
      <td height="32"> <input name="emergencyphone" type="text" size="20">
    </td></tr>

    <tr><td align=right valign=top>Individual Hat Draw ($35)<sup>*</sup></td>
          <td height="20"></td> 
          <td height="20">
            <input name="hat" type="radio" value="yes">Yes, I plan on attending the Hat Draw&nbsp;<br>
            <input name="hat" type="radio" value="No">No, I am unable to attend the Hat Draw
            <br><br><font color=green>The Post Hopu Kauai Hat Draw is on November 15, 2008. <a href="/hopu/register_hat.asp">Hat Registration</a> is now separate from Hopu registration.</font>
    </td></tr>

    <tr><td align=right valign=top><br>Dietary Preference<sup>*</sup></td> 
      <td height="65"></td>
      <td height="65"><br>
         <input name="diet" type="radio" value="Ommivore"> Omnivore&nbsp;&nbsp;
         <input name="diet" type="radio" value="Veggie"> Veggie&nbsp;&nbsp;
         <input name="diet" type="radio" value="Vegan"> Vegan
         <br><br><font color=green>If you have any additional specific dietary needs, please email hopu@hawaiiultimate.com</font>
    </td></tr>

    <tr><td colspan=3>&nbsp;</td></tr>

    <tr><td align=right valign=top>Estimate Your Skill Level<sup>*</sup></td>
          <td></td>
          <td>
            <input type="radio" name="skill" value="1">1......  Enthusiastic Green Beginner<br>
            <input type="radio" name="skill" value="2">2<br>
            <input type="radio" name="skill" value="3">3 <br>
            <input type="radio" name="skill" value="4">4 <br>
            <input type="radio" name="skill" value="5">5...... Regular League Player<br>
            <input type="radio" name="skill" value="6">6 <br>
            <input type="radio" name="skill" value="7">7 <br>
            <input type="radio" name="skill" value="8">8 <br>
            <input type="radio" name="skill" value="9">9 <br>
            <input type="radio" name="skill" value="10">10...... World's Caliber Player (I'm sponsored)</p>
    </td></tr>

    <tr><td align=right valign=top><br>Are you willing to volunteer?<sup>*</sup></td> 
       <td height="47"></td>
       <td valign=top height="47"><br>
          <input name="volunteer" type="radio" value="Yes"> Yes&nbsp;&nbsp;
          <input name="volunteer" type="radio" value="No"> No&nbsp;&nbsp;
          <br><br><font color=green>Aloha, or unconditional love, is definitive of the Hawaiian lifestyle. Volunteerism shares aloha. Are you willing to volunteer (e.g., serve food or fill water) for one hour during Hopu Ka Lewa?</font>
    </td></tr>



    <tr><td colspan=3 valign=top><hr><center><b>Waiver</b></center>

<p>I acknowledge that an Ultimate event is an extreme test of a persons physical and mental limits and carries with it the potential for death, serious injury and property loss.  I HEREBY ASSUME THE RISK OF PARTICIPATING IN THE 
Hopu Ka Lewa ULTIMATE TOURNAMENT.  I certify that I am physically fit, have trained sufficiently for participation in 
said tournament and have NOT been advised against participation in said 
tournament, Ultimate events or physical activity by a qualified medical person.  I acknowledge that my statement on this AWRF are being accepted by H.U.L.A. 
in consideration for allowing me to participate in this Ultimate Tournament, and are being relied upon by H.U.L.A. and the promoters, insurer(s), other participants, operators, officials, any sponsors, advertisers, owners, lessees and lessors of premises used to conduct the event.

<p>In consideration for allowing me to participate in Hopu Ka Lewa, I hereby take the following action for myself, my executors, administrators, heirs, next of kin, successors and assigns:

<p>(a)	I AGREE to abide by the rules of Ultimate and the Bylaws adopted by H.U.L.A. and the Tournament Committee, and I acknowledge that my participation in this event may be revoked or suspended for violations thereof.

<p>(b)	I WAIVE, RELEASE, AND DISCHARGE from any and all claims of liabilities for death, personal injury, property damage, theft or damage of any kind, which arise out of or may be related to my participation in 
said tournament.  THE FOLLOWING PERSONS OR ENTITIES: H.U.L.A., Tournament Director and committee, event volunteers, all State, city, and county offices, the lessee and lessor of the premises used to conduct the event, and the officers, directors, employees, representatives, and agents of any of the above.

<p>(c)	I AGREE NOT TO SUE any of the persons or entities mentioned above in (b) for any of the claims or liabilities that I have waived, released or discharged herein.

<p>(d)	I AGREE TO INDEMNIFY AND HOLD HARMLESS the persons or entities mentioned above in (b) for any of the claims made or liabilities assessed against them as a result of my actions during or related to the Ultimate Tournament.
    </td></tr>

    <tr><td valign=top colspan=3 height="35"><br>
		<center><input name="Waiver" type="radio" value="Accept"> I Accept&nbsp;&nbsp;</center>
    </td></tr>


    <tr><td colspan=3 height="61"><br><hr><br><center><b>Payment</b></center></td></tr>
<tr><td height="22">Payment Fee<sup>*</sup></td> <td height="22"></td> 
  <td height="22">
	<select name=feepay>
	 <option value="blank">
	 <option value="0">Individual (one of three pre-paid with team bid): $0
	 <option value="125">Individual Player Fee: $125
	 <option value="60">Guest Fee (all days): $60
	 <option value="40">Guest Fee (two days): $40
	 <option value="20">Guest Fee (one day): $20
	 </select>
    </td></tr>

    <tr valign=top><td height="90"><br><input name="Payment" type="radio" value="Check"> Pay by Check</td> 
      <td height="90"></td>
	<td valign=top height="90"><br>Please send your check (payable to "Hawaii Coed Ultimate") to
		<dd>Hopu Ka Lewa<dt>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
    c/o Megan Grimshaw</dt>
		<dd>3518 McCorriston St<dd>Honolulu, HI 96815</td></tr>
<td valign=top height="15"></td></tr>


    <tr><td height="1"></td></tr>
    <tr><td colspan=3 height="20">
	<p><input name="Payment" type="radio" value="CreditCard"> Pay by Credit Card&nbsp;&nbsp;
    </td></tr>



    <tr><td colspan="3" height="72"><br><hr><br><center>
      <input type="submit" value="Submit Registration and Continue to Payment"></center></td></tr>

  </table></center></td></tr>

  </table>
</form>

