
  <form method="post" action="regmailer_hat.asp">

  <table border=0 width="100%">
  <tr><td><center>
   <table border=0>
    <tr><td colspan=3 height="16">
       <center>
         <font color=blue size=+2>Hat Draw Registration Form</font><br><hr>
       </center>
   </td></tr>

    <tr>
      <td width="35%" align=right valign=top>First Name<sup>*</sup></td>
      <td width="5%"">&nbsp;&nbsp;</td> 
      <td width="60%"> <input name ="firstname" type="text" size="20">
    </td></tr>

    <tr><td align=right valign=top>Last Name<sup>*</sup></td>
      <td height="22"></td> 
      <td height="22"> <input name="lastname" type="text" size="20">
    </td></tr>

    <tr><td align=right valign=top>Sex<sup>*</sup></td> <td height="20"></td> 
      <td height="20">
         <input name="gender" type="radio" value="Male"> Male&nbsp;&nbsp;
         <input name="gender" type="radio" value="Female"> Female
    </td></tr>

    <tr><td colspan=3>&nbsp;</td></tr>
 
    <tr><td align=right valign=top>Email<sup>*</sup></td>
      <td height="22"></td> 
      <td height="22"> <input name="email" type="text" size="20">
    </td></tr>

    <tr><td align=right valign=top>Phone Number<sup>*</sup></td>
      <td height="22"></td> 
      <td height="22"> <input name="phone" type="text" size="20">
    </td></tr>

    <tr><td align=right valign=top>Age<sup>*</sup></td>
       <td height="20"></td> 
       <td height="20">
          <input name="age" type="radio" value="Over21"> Over 21&nbsp;&nbsp;
          <input name="age" type="radio" value="Under21"> Under 21
     </td></tr>

    <tr><td colspan=3>&nbsp;</td></tr>

    <tr><td align=right valign=top>Emergency Contact Name<sup>*</sup></td>
      <td height="32"></td> 
      <td height="32"> <input name="emergencyname" type="text" size="20">
    </td></tr>

    <tr><td align=right valign=top>Emergency Contact Phone<sup>*</sup></td> 
      <td height="32"></td> 
      <td height="32"> <input name="emergencyphone" type="text" size="20">
    </td></tr>

    <tr><td align=right valign=top><br>Dietary Preference<sup>*</sup></td> 
      <td height="65"></td>
      <td height="65"><br>
         <input name="diet" type="radio" value="Ommivore"> Omnivore&nbsp;&nbsp;
         <input name="diet" type="radio" value="Veggie"> Veggie&nbsp;&nbsp;
         <input name="diet" type="radio" value="Vegan"> Vegan
         <br><br><font color=green>If you have any additional specific dietary needs, please email hopu@hawaiiultimate.com</font>
    </td></tr>

    <tr><td colspan=3>&nbsp;</td></tr>

    <tr><td align=right valign=top>Estimate Your Skill Level<sup>*</sup></td>
          <td></td>
          <td>
            <input type="radio" name="skill" value="1">1......  Enthusiastic Green Beginner<br>
            <input type="radio" name="skill" value="2">2<br>
            <input type="radio" name="skill" value="3">3 <br>
            <input type="radio" name="skill" value="4">4 <br>
            <input type="radio" name="skill" value="5">5...... Regular League Player<br>
            <input type="radio" name="skill" value="6">6 <br>
            <input type="radio" name="skill" value="7">7 <br>
            <input type="radio" name="skill" value="8">8 <br>
            <input type="radio" name="skill" value="9">9 <br>
            <input type="radio" name="skill" value="10">10...... World's Caliber Player (I'm sponsored)</p>
    </td></tr>



    <tr><td colspan=3 valign=top><hr><center><b>Waiver</b></center>

<p>I acknowledge that an Ultimate event is an extreme test of a persons physical and mental limits and carries with it the potential for death, serious injury and property loss.  I HEREBY ASSUME THE RISK OF PARTICIPATING IN THE 
Hopu Ka Lewa ULTIMATE TOURNAMENT.  I certify that I am physically fit, have trained sufficiently for participation in 
said tournament and have NOT been advised against participation in said 
tournament, Ultimate events or physical activity by a qualified medical person.  I acknowledge that my statement on this AWRF are being accepted by H.U.L.A. 
in consideration for allowing me to participate in this Ultimate Tournament, and are being relied upon by H.U.L.A. and the promoters, insurer(s), other participants, operators, officials, any sponsors, advertisers, owners, lessees and lessors of premises used to conduct the event.

<p>In consideration for allowing me to participate in Hopu Ka Lewa, I hereby take the following action for myself, my executors, administrators, heirs, next of kin, successors and assigns:

<p>(a)	I AGREE to abide by the rules of Ultimate and the Bylaws adopted by H.U.L.A. and the Tournament Committee, and I acknowledge that my participation in this event may be revoked or suspended for violations thereof.

<p>(b)	I WAIVE, RELEASE, AND DISCHARGE from any and all claims of liabilities for death, personal injury, property damage, theft or damage of any kind, which arise out of or may be related to my participation in 
said tournament.  THE FOLLOWING PERSONS OR ENTITIES: H.U.L.A., Tournament Director and committee, event volunteers, all State, city, and county offices, the lessee and lessor of the premises used to conduct the event, and the officers, directors, employees, representatives, and agents of any of the above.

<p>(c)	I AGREE NOT TO SUE any of the persons or entities mentioned above in (b) for any of the claims or liabilities that I have waived, released or discharged herein.

<p>(d)	I AGREE TO INDEMNIFY AND HOLD HARMLESS the persons or entities mentioned above in (b) for any of the claims made or liabilities assessed against them as a result of my actions during or related to the Ultimate Tournament.
    </td></tr>

    <tr><td valign=top colspan=3 height="35"><br>
		<center><input name="Waiver" type="radio" value="Accept"> I Accept&nbsp;&nbsp;</center>
    </td></tr>


    <tr valign=top><td height="90">&nbsp;</td>
      <td height="90"></td>
	<td valign=top height="90"><br>Please send your check (payable to "Lori Middlebrook") to
		<dd>Middlebrook
		<dd>PO Box 335
		<dd>Lawai, HI 96765</td></tr>
<td valign=top height="15"></td></tr>


    <tr><td height="1"></td></tr>



    <tr><td colspan="3" height="72"><br><hr><br><center>
      <input type="submit" value="Submit Registration"></center></td></tr>

  </table></center></td></tr>

  </table>
</form>

