<!--#include file="../include/blurb_border_top.inc"-->
   The Hawaii Ultimate League Association (HULA) is a non-profit organization
   founded in 1993 but with roots going back two decades. It was formed to
   provide continuity and organization for the ad-hoc disc activities taking
   place on the islands.
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
   The purpose of HULA is to encourage and promote disc-related activities
   including Ultimate, Disc Golf, Freestyle, Double Disc Court and Hacky Sack
   as well as to promote the Spirit of the Game concept through regular league play,
   tournaments and educational programs for both youth and adults.
   (<i>From the Bylaws of Hawaii Ultimate League Association, as amended 5/31/93</i>)<br>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
   HULA's members are dues-paying players who have participated in
   league within the past two seasons. HULA's leaders are elected by
   the general membership for two-year terms on the Board of Directors.
   The HULA Commissioner is selected from the most
   spirited team of the previous league season.
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
   HULA events include the following:
   <br><img src="1p.gif" height="5" width="1"><br>
   &nbsp;&#149;&nbsp;<b>City League</b> - City league takes place in both spring
   and fall. Each season runs for ~16 weeks, and has 6-8 teams. League
   culminates in a final tournament.  Teams are coed and are selected by
   open draft that encourages players to form new bonds of friendship and
   camaraderie each season.

   <br><img src="1p.gif" height="5" width="1"><br>
   &nbsp;&#149;&nbsp;The world-famous <b>Kaimana Klassic Tournament</b> - The
   Kaimana Klassic began in 1988 with just a few local teams and a team from
   California. It has grown into one of the premier tournaments in the United
   States for Open and Women's divisions, drawing over 25 teams from around the
   world. The three-day tournament is held over Presidents Day weekend, with
   breakfast, dinner, parties, and beach camping all provided on site.

   <br><img src="1p.gif" height="5" width="1"><br>
   &nbsp;&#149;&nbsp;<b>Hopu Ka Lewa</b> - Hopu, as it is affectionately called
   by players, is a low-key, coed tournament held in April. Hopu Ka Lewa, which
   means "Catch the Sky," began in 1999 as an opportunity to share Hawai'i's
   spirited coed play with guests to the islands. Though modeled after the Kaimana
   Klassic, with food, parties, and camping provided on site, Hopu caters to the
   mixed (coed) division in Ultimate, encouraging spirited play and sportsmanship
   above all else.

   <br><img src="1p.gif" height="5" width="1"><br>
   &nbsp;&#149;&nbsp;<b>Hawaii State Overall Championships</b> - This is an annual
   event which introduces HULA members to non-ultimate disc sports such as
   double-disc court, discathon, disc golf, and throwing accuracy. HSO usually
   takes place in July of each year.

   <br><img src="1p.gif" height="5" width="1"><br>
   HULA also sponsors various member-initiated hat draws and ad hoc tournaments.
   In the last few years, these have included the <b>Bok Choy</b> hat draw, the
   <b>Loco Moco</b> tournament, a <b>Savage Sevens</b> tournament, plus various
   outer-island hat draws. Traditionally, there is a large off-island hat draw
   held the weekend before or after the Kaimana Klassic and Hopu Ka Lewa tournaments.
 <!--#include file="../include/blurb_border_bottom.inc"-->
