<!--#include file="../include/blurb_border_top.inc"-->
                <P>The Hawaii Ultimate League Association announces the establishment
                of the HULAship Program, which is designed to lend financial assistance to
                individuals who are interested in playing in the Kaimana Klassik or Hopu Ka
                Lewa.  Since we are not the IRS, and therefore not privy to your personal
                financial information, we ask that only those who genuinely need assistance apply.
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
              <p>&nbsp;&#149;&nbsp;The deadline for applications is 2 months prior to a tournament.
                 Applications must be postmarked no later than 2 months prior if they are mailed.
                 Emailed applications are also acceptable, as are hand deliveries.
                     <UL><LI>For US mail, send to:
                           <dd>Jena Kline
			   <dd>PO Box 240638
                           <dd>Honolulu, HI 96824-0638</li>
                         <LI>For email, send to:  <A HREF="mailto:jtkline@hotmail.com">jtkline@hotmail.com</A></LI>
                         <LI>For hand deliveries, give to:  Jena Kline</LI>
                     </UL>

              <p>&nbsp;&#149;&nbsp;HULAships are restricted to current dues-paying HULA members
                 (within the past 2 league seasons).  An exception to this dues-paying stipulation
                 is made for neighbor island players.  Former HULA members may also apply, but they
                 will be considered only under special circumstances (which must be cited).
              <p>&nbsp;&#149;&nbsp;Financial need must be described in narrative form.  While you
                 are not obligated to disclose personal financial data, be aware that the more
                 information we (the committee) have, the better we are able to assess your true
                 financial need.
              <p>&nbsp;&#149;&nbsp;If a HULAship is granted, we expect that you will be able to
                 volunteer in some fashion during the tournament.
              <br><br>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
                <B><P>Your application should consist of three paragraphs and/or sections
                   (the length of which you can choose), addressing the following topics:</P>
                   <UL><LI>Why do you need financial assistance?</LI>
                       <LI>How much financial assistance do you need? (Full=$120, Partial=?)</LI>
                       <LI>Include a statement pertaining to ultimate (i.e. a funny story, what it
                           means to you, what is the meaning of the game, etc.)</LI></UL>
                   </UL>

                <P>Be sure to include your name and contact information.</b><br><br>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
                <P>After all applications are received, HULAship selection committee members
                   will review applications during a period of two weeks.  All applicants will
                   be notified 30 days prior to the tournament as to their HULAship award status.</P>

                <P>A total of $1,000 has been allotted to the Hulaship program.  The number and
                   value of awards given will, of course, depend upon the number of applicants.
                <br><br>
<!--#include file="../include/blurb_border_bottom.inc"-->
