<!--#include file="../include/blurb_border_top.inc"-->
   Meetings are open to all HULA members.  For more information, please
   visit this web page or contact any <a href="hula_board.asp">HULA board member</a>.
   <br><br>

<center><table border=0>
<tr><td colspan=3><hr></td></tr>
<tr><td valign=top>
&nbsp;&#149;&nbsp;<a href="/documents/minutes_012207.pdf" target=minutes>Jan 22, 2007 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_050507.pdf" target=minutes>March 5, 2007 minutes</a><br>
&nbsp;&#149;&nbsp;<a href="/documents/minutes_043007.pdf" target=minutes>April 30, 2007 minutes</a><br>
</tr>
<tr><td colspan=3><hr></td></tr>
<tr><td valign=top>
   &nbsp;&#149;&nbsp;<a href="/documents/agenda_011606.pdf" target=minutes>Jan 16, 2006 agenda</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_030506.pdf" target=minutes>Mar 05, 2006 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_042306.pdf" target=minutes>Apr 23, 2006 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/agenda_052406.pdf" target=minutes>May 24, 2006 agenda</a><br>
   </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td valign=top>
   &nbsp;&#149;&nbsp;<a href="/documents/agenda_072306.pdf" target=minutes>Jul 23, 2006 agenda</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_081706.pdf" target=minutes>Aug 17, 2006 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_100906.pdf" target=minutes>Oct 09, 2006 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_120406.pdf" target=minutes>Dec 04, 2006 minutes</a><br>
</tr>
<tr><td colspan=3><hr></td></tr>
<tr><td valign=top>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_013005.pdf" target=minutes>Jan 30, 2005 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_030605.pdf" target=minutes>Mar 06, 2005 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_042405.pdf" target=minutes>Apr 24, 2005 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_061005.pdf" target=minutes>Jun 10, 2005 minutes</a><br>
   </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td valign=top>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_072405.pdf" target=minutes>Jul 24, 2005 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_082105.pdf" target=minutes>Aug 21, 2005 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_100205.pdf" target=minutes>Oct 02, 2005 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/agenda_120105.pdf" target=minutes>Dec 1, 2005 agenda</a><br>
</tr>
<tr><td colspan=3><hr></td></tr>
<tr><td valign=top>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_081904.pdf" target=minutes>Aug 19, 2004 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_092204.pdf" target=minutes>Sep 22, 2004 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_110304.pdf" target=minutes>Nov 03, 2004 minutes</a><br>
   &nbsp;&#149;&nbsp;<a href="/documents/minutes_121204.pdf" target=minutes>Dec 12, 2004 minutes</a><br>
</tr>
<tr><td colspan=3><hr><br></td></tr>
</table></center>

<!--#include file="../include/blurb_border_bottom.inc"-->
