<!--#include file="../include/blurb_border_top.inc"-->

<TABLE CELLSPACING=0 BORDER=0 cellpadding="5">
<TR><TD>
<B>HULA BOARD</B></TD><TD><B>POSITION</B></TD><TD><B>EMAIL ADDRESS</B></TD></TR>
<TR><TD valign=top>Dave Strang</TD>
  <TD valign=top>President</TD>
  <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "dstrang";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>dstrang<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
    <script language="JavaScript">
    <!--
      var username = "president";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>president<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</TD></TR>

<TR><TD valign=top>Laura Gilda</TD>
  <TD valign=top>Vice-President</TD>
  <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "lgilda";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>lgilda<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
    <script language="JavaScript">
    <!--
      var username = "vicepresident";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>vicepresident<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</TD></TR>

<TR><TD valign=top>Jason Sickmiller</TD>
  <TD valign=top>Treasurer</TD>
  <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "jsickmiller";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>jsickmiller<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
    <script language="JavaScript">
    <!--
      var username = "treasurer";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>treasurer<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</TD></TR>

<TR><TD valign=top>Megan Grimshaw</TD>
  <TD valign=top>Secretary</TD>
  <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "mgrimshaw";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>mgrimshaw<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
    <script language="JavaScript">
    <!--
      var username = "secretary";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>secretary<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</TD></TR>

<TR><TD valign=top>Aaron Rosa</TD>
 <TD valign=top>Board Member</TD>
 <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "arosa";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>arosa<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</TD></TR>
<TR><TD valign=top>Alex Globerson</TD>
  <TD valign=top>Board Member</TD>
  <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "agloberson";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>agloberson<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</TD></TR>
<TR><TD valign=top>BJ Philmus</TD>
  <TD valign=top>Board Member</TD>
  <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "bjphilmus";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>bjphilmus<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</TD></TR>
<TR><TD valign=top>Frances Ajo</TD>
  <TD valign=top>Board Member</TD>
  <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "fajo";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>fajo<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</TD></TR>
<TR><TD valign=top>Jena Kline</TD>
  <TD valign=top>Board Member</TD>
  <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "jkline";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>jkline<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</TD></TR>
<TR><TD valign=top>Kim Weersing</TD>
  <TD valign=top>Board Member</TD>
  <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "kweersing";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>kweersing<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</TD></TR>
<TR><TD valign=top>Mondo Chun</TD>
  <TD valign=top>Board Member</TD>
  <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "mchun";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>mchun<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</TD></TR>

<tr><td colspan="3"><hr></td></tr>
<TR><TD valign=top>Dallas Willett</TD>
  <TD valign=top>Webmaster</TD>
  <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "dwillett";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>dwillett<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
    <a href="mailto:dwillett@hawaiiultimate.com">dwillett@hawaiiultimate.com</A><br>
    <script language="JavaScript">
    <!--
      var username = "webmaster";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>webmaster<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</TD></TR>
<TR><TD valign=top>Jena Kline</TD>
  <TD valign=top>Kaimana Liaison</TD>
  <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "kaimana";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>kaimana<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</TD></TR>
<TR><TD valign=top>Graham McNeil<br>Jess Kaneshiro<br>Weston Willard</TD>
  <TD valign=top>Spring '07 League Commissioners</TD>
  <TD valign=top>
    <script language="JavaScript">
    <!--
      var username = "commissioner";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
    <b>commissioner<img src=/beta/images/at.gif>hawaiiultimate.com</b>
    </noscript>
</td></tr>
</TABLE>
<!--#include file="../include/blurb_border_bottom.inc"-->

