<!--#include file="../include/blurb_border_top.inc"-->

   <br>
   &nbsp;&#149;&nbsp;<a href="documents/hula_commish.pdf" target=documents>League Commissioner's Handbook, 1st Ed. - May 1999</a><br><br>
   &nbsp;&#149;&nbsp;<a href="documents/hula-welcome0903.pdf" target=documents>HULA Welcome Letter - Sept 2003</a><br><br>
   &nbsp;&#149;&nbsp;<a href="documents/hula-corp-fields04a.pdf" target=documents>Central Oahu Field Use - Jan-Aug 2004</a><br><br>
   &nbsp;&#149;&nbsp;<a href="documents/hula-aloha-dstrang.pdf" target=documents>Aloha Grant, Oct '03 - D.Strang, College Series</a><br><br>
   &nbsp;&#149;&nbsp;<a href="documents/hula-aloha-jkline.pdf" target=documents>Aloha Grant, Oct '03 - J.Kline, Fall Hat Draw</a><br><br>
   &nbsp;&#149;&nbsp;<a href="documents/hula-aloha-bdurand.pdf" target=documents>Aloha Grant, Oct '03 - B.Durand, Kapaolono Restoration</a><br><br>
   &nbsp;&#149;&nbsp;<a href="documents/hula-aloha-llott.pdf" target=documents>Aloha Grant, Oct '03 - L.Lott, Wahine Weekend</a><br><br>
   &nbsp;&#149;&nbsp;<a href="documents/hula-yellowred-cards.pdf" target=documents>Yellow/Red Card Proposal - Nov 19, 2003</a><br><br>
   &nbsp;&#149;&nbsp;<a href="documents/ACL.pdf" target=documents>Knee Health - April 2005</a><br><br>
   &nbsp;&#149;&nbsp;<a href="documents/PEPExercises_ACL.pdf" target=documents>Knee-Strengthening Exercises - April 2005</a><br><br>
   &nbsp;&#149;&nbsp;<a href="documents/hula-commish_2nd-ed.pdf" target=documents>League Commissioner's Handbook, 2nd Ed. - June 2005</a><br><br>


<!--#include file="../include/blurb_border_bottom.inc"-->
