<!--#include file="../include/blurb_border_top.inc"-->
   <p><center><b>Got a great idea for improving or expanding ultimate or disc-related
   activities?  Get a grant from HULA!</b></center>

   <p>The Hawaii Ultimate League Association is proud to offer its initial
   Ultimate Aloha Grants Program. Goals of the Aloha Grants Program are to
   promote growth in Ultimate and Ultimate Spirit in Hawaii, to create links
   between HULA and the local community, to serve members’ needs, and to create
   documentation that will inspire others to further innovation and excellence.

   <p>HULA’s Ultimate Aloha Grant program is looking for creative ideas and
   programs to help promote the sport, offering funds of up to $500 per project.

   <p>To apply for a Aloha Grant, please answer the questions below and submit
   your application to PO Box 240638, Honolulu, Hawaii 96824-0638 or
   <A HREF="mailto:treasurer@hawaiiultimate.com">treasurer@hawaiiultimate.com</A>.
   Summaries of applications received will be posted on the HULA web-site.
   <B>Email is preferred</B>.

   <p>Applicants may request a grant of up to $500.<BR><br>

<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
                <b>RULES FOR APPLYING:</b><ol>
                <li>Make the Grant Selection Committee happy, keep answers SHORT! (yet complete)
                <li>There are no "right" answers – understand that the Grant Selection Committee is not looking for a particular answer to any question.
                <li>Don’t worry if you can’t answer all questions – do your best. 
                <li>Respect the decisions of the hard working volunteer committee. 
                <li>If you are awarded a grant, you will:<ol>
                    <li>Write an article about your completed project for the HULA web site, and 
                    <li>Submit pictures, newspaper articles, programs and other documents for the HULA web site.</ol>
                </ol>
                <p><b>SUBMISSION DEADLINE:</b>
                <br>Application for an activity between July thru Dec: <b>Deadline is April 15th</b>
                <br>Application for an activity between Jan thru June: <b>Deadline is October 31th</b>
              <br><br>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
   <p><b>HULA ULTIMATE ALOHA GRANTS PROGRAM APPLICATION</b>
   <p><b>PART I – CONTACT INFO</b>
   <br>Title of your Idea/Project/Program:
   <br>Your Name:
   <br>Group (if you’re part of an organized entity):
   <br>Mailing Address:
   <br>Phone:
   <br>E-mail:

   <p><b>PART II - DESCRIPTION</b>
   <br>What is your idea, project or program? 
   <br>What sparked the idea for your proposal? 
   <br>How does your idea/proposal fill an unmet need in Ultimate, other disc related activities and/or the broader community?

   <p><b>PART III – DETAILS</b>
   <br>How feasible is your project, i.e. what is the likelihood of you completing this project – with or without a ALOHA Grant? 
   <br>When will the project happen? When will it be completed?
   <br>Who is the "project sponsor", or primary person responsible? 
   <br>Who else is involved (if it is a group)?

   <p><b>PART IV – RESOURCES</b>
   <br>What resources are needed for the project completion? List all resources necessary including facilities, people, money, equipment, etc… 
   <br>Of these resources, which do you already have secured? Which do you foresee as being difficult to obtain?
   <br>What is the amount of your ALOHA Grant request?
   <br>How will this amount be used?

   <p><b>PART V – CONCLUSION</b>
   <br>Please write a short SUMMARY for the web page. 
   <br>Please give us a BRIEF ultimate "resume": What ultimate experience(s) are relevant to the nature of your project? What ultimate projects have you undertaken and/or what leadership roles have you held, if any? You may also include relevant non-ultimate activities.
   <br><br>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
                <p>Mahalo and Aloha to all!

                <p>Thanks for your application and for your contribution to the sport of ultimate! If we have any questions about your application we may call or write during the evaluation period.

                <p>Sincerely, The HULA Grant Committee<BR><br>
<!--#include file="../include/blurb_border_bottom.inc"-->
