<!--#include file="../include/blurb_border_top.inc"-->
<center>
<table border=0>
<tr><td width="35%"><a name=top><b>2004&nbsp;Candidates</b></a>
      <li><b><a href="#bcushman">Buffy&nbsp;Cushman</a>&nbsp;-&nbsp;42</b>
      <li><b><a href="#fdabrosky">Frank&nbsp;Dabrosky</a>&nbsp;-&nbsp;33</b>
      <li><b><a href="#bdurand">Bartlett&nbsp;Durand</a>&nbsp;-&nbsp;48</b>
      <li><b><a href="#jhillcrest">John&nbsp;Hillcrest</a></b>&nbsp;-&nbsp;17
      <li><b><a href="#ljerome">Leigh&nbsp;Jerome</a></b>&nbsp;-&nbsp;22
      <li><b><a href="#rkinslow">Rob&nbsp;Kinslow</a></b>&nbsp;-&nbsp;12
      <li><b><a href="#ilobos">Ignacio&nbsp;Lobos</a>&nbsp;-&nbsp;32</b>
      <li><b><a href="#bphilmus">BJ&nbsp;Philmus</a></b>&nbsp;-&nbsp;31
      <li><b><a href="#dstrang">Dave&nbsp;Strang</a>&nbsp;-&nbsp;47</b>
    </td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td>The annual general HULA meeting and board elections were
	held on Saturday, May 22, at Waipio Fields, 1-2 PM.
	Newly elected board members are <b>Bartlett Durand, Buffy
	Cushman, Dave Strang, Frank Dabrosky, and Ignacio Lobos</b>.
	There were a total of 59 ballots cast (52 at the fields and 7
	via email).  Vote totals for all nominees are listed at left.
	The HULA Bylaw amendment to separate HULA membership dues from
	league fees passed with 42 votes in favor of the change and 9
	votes opposed to the change.
	Congratulations to the new Board and thanks to all nominees.
 	To contact the HULA Board of Directors, please email
	<b>hulaboard<img src=at.gif>hawaiiultimate.com</b>.</td>
</tr>
</table>
</center>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
<img src="faces/BuffyCushman.jpg" align=right height=150 width=113>
<a name="bcushman"><b>Buffy Cushman</b></a> (<i>CURRENTLY OFF ISLAND</i>)
<ul>
<li>Has served on the HULA Board of Directors since 2000 as HULA
    Treasurer, HULA Secretary and is the current HULA Co-Vice President.
<li>Kaimana Klassik Tournament Director the past 2 years.
<li>One of the founding members of the Sunday evening learners league.
<li>Has supported and organized numerous womens clinics as well as
    contributed to the overall growth of ultimate in Hawaii.
<li>Has represented Hawaii as a member of Hana Hou at regionals and WUCC
    2002.
</ul>

<p><i><a href="#top">back to top</a></i>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
<img src="faces/FrankDabrosky.jpg" align=right height=150 width=113>
<a name="fdabrosky"><b>Frank Dabrosky</b></a>

<p>I originally started playing Ultimate in the summer of 2001 in my
home state of New Jersey.  I had been playing the deep position because
of my inexperience and because of my speed.  I came to Hawaii and
played in the Bok Choy tournament before my school started up and met
up with Brent and Shane through that tournament.  I joined the fall
league while running cross country for my school and later in the
spring joined the league.  I started up an Ultimate team at my school
from scratch to have more players to play with.  We made a team to
play in the Hopu Ka Lewa tournament and made it to the quarterfinals
while winning the spirit award.  The next two years I played in the
Kaimana Klassik as well as continued with my team at Chaminade for the
Hopu Ka Lewa tournament.  Every summer I come home to play in the same
summer league to captain it to bring some spirit out to the league as
well as to help improve my own skills more.

<p><i><a href="#top">back to top</a></i>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
<img src="faces/BartlettDurand.jpg" align=right height=150 width=113>
<a name="bdurand"><b>Bartlett Durand</b></a>

<p>I've was a Board member this past term and would like to serve another.  We 
are in the midst of something exciting here with Hawaii ultimate, and would 
like to ensure that we keep everyone's interests in mind while we move 
forward.  Examples of what I've accomplished: creation of The First Annual 
Bok Choy International Invitational Super Duper Hat Draw (not to mention 
TROTFABCIISDHD).  Upgrading the insurance.  Leading the renovation of the 
Kapaolono Fields.  Anyway, I think this year's board has done some 
tremendous things and I would like the opportunity to continue the work we 
began or continued.

<p><i><a href="#top">back to top</a></i>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
<img src="faces/JohnHillcrest.jpg" align=right height=150 width=113>
<a name="jhillcrest"><b>John Hillcrest</b></a>

<p>Aloha Hawaii Ultimate Community.  I am John Hillcrest.  I was born in 
England, lived in Canada for a few years & spent most of my life in Duluth, 
MN.  I started playing Ultimate when I was 19. I am 42 years old now and 
ultimate has already given me 23 years of great memories, friends and 
experiences.  I've competed and been involved with Ultimate teams and 
community leagues in Canada, Europe, Mexico and the United States.  We moved 
to Hawaii in Nov. of 2001 to coordinate the World Ultimate Club 
Championships-Hawaiian Outreach Program (HOP).   My family and I have been 
involved with Disc Games Youth Outreach programs for the past 10 years, and 
continue to instruct youth groups, classrooms or any keiki group willing to 
learn the values and skills of Disc Games.  With a sincere spirit of 
gratitude for the memories given and a strong dedication to the youth of 
Hawaii, I offer myself to you.  I am a big picture visionist.  If elected, I 
will try to see that the opinions of ALL members are heard and thoughtfully 
considered.  I truly believe the game & spirit of ultimate is meant for 
everyone. Ultimate saved my life.

<p>Mahalo for your consideration, John Hillcrest

<p><i><a href="#top">back to top</a></i>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
<img src="faces/LeighJerome.jpg" align=right height=150 width=113>
<a name="ljerome"><b>Leigh Jerome</b></a>

<p>I was born quite young but as each year goes by, I get a little older.
I am proud of this natural progression towards maturity - it seems to come
to me quite effortlessly.   I am also a solid underachiever, which affords
me with boundless, unexpended potential.  I've been to school extensively,
involved myself in social advocacy, traveled a bit and fallen in love -
these are my finer points.  I've also had my share of cross words on the
field; had my puking head held out of a New York cab; and, I run late for
work almost every day, so I guess it all kind of a wash.  I do research,
write, weld and play a lot of ultimate.  Our ultimate community is
important to me.  I'm pragmatic, fair and, perhaps most critical to the
perspective I could bring to the board, I am a previous Schloupe winner.
Hope this works for you.

<p><i><a href="#top">back to top</a></i>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
<img src="faces/RobKinslow.jpg" align=right height=150 width=113>
<a name="rkinslow"><b>Rob Kinslow</b></a>

<p>Aloha, i've been playing disc sports since before tree bark. Umm,
maybe not that long. I first started playing at KKII. One year, it
rained so hard we had a mini lake next to the fields. We all just ran
and layout into this 2 ft pool of water and mud. That was a hi-lite
memory. I came here b/c i loved playing ultimate here. Now, I make
films about Hawai`i frisbee. HULA has supported this and we've
collaborated in producing 6 videos about KKXV. Ultimate teaches
honesty in action. It's a great sport to learn conflict
resolution skills. Play Ulti. ((o;'

<p><i><a href="#top">back to top</a></i>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
<img src="faces/IgnacioLobos.jpg" align=right height=150 width=113>
<a name="ilobos"><b>Ignacio Lobos</b></a>

<p>I like Ultimate so much that I always bring cones to pick-up (three
years at Ala Moana, and now at Kapiolani). My lines are finally (well,
almost) straight! I try not to hog the disc anymore and I'm going long
again. No handling for this guy.

<p>But when it comes to HULA and Ultimate, I feel I've done plenty of
handling for our organization. I served on the HULA board for two years,
I have volunteered for thankless jobs at Kaimana, I have been a team
captain, I have helped put teams together, and I was one of the Hopu
co-founders, and director for three years.

<p>I wasn't planning to run for a HULA spot, but some of my Ultimate
friends encouraged me to represent them. I'm running for them because I
know how much they love this game, and how much they want to ensure that
HULA remains a viable organization for all of us.

<p><i><a href="#top">back to top</a></i>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
<img src="faces/BJPhilmus.jpg" align=right height=150 width=113>
<a name="bphilmus"><b>BJ Philmus</b></a>

<p>A direct decendant of Eric the Pale, BJ has navigated the globe on a 
wooden raft he made out of old oak trees with human hair as twine and 
the skin of his first dog, a st. bernard, as the sail. He landed on 
Waimea beach two years ago and discovered a strange sport practiced by 
the native pale people that utilized a flat object. Thinking it was a 
weird pie tin BJ went to investigate. He soon got sucked up into the 
community and was widely accepted because he was paler than all. His 
first experience with the disc throwers was the now infamous trophy 
controversy of '02. This inspired him to become further consumed in 
the sport of the upside down pie tin in order to right the injustices 
he saw. With the small boat he built and the sense of duty and honor 
instilled in him by the teachings of Smealt the Old he declared his 
candidacy for the HULA board.

<p><i><a href="#top">back to top</a></i>
<!--#include file="../include/blurb_border_bottom.inc"-->

<!--#include file="../include/blurb_border_top.inc"-->
<img src="faces/DaveStrang.jpg" align=right height=150 width=113>
<a name="dstrang"><b>Dave Strang</b></a>

<p>I was initially reluctant to get involved in the ultimate league.  
After some gentle coaxing, I discovered an amazing sport and an amazing 
group of people.  I play this game for fun, spirit, and camaraderie, 
and I've tried to instill that as much as possible into HULA.  I've 
been a team captain, league commissioner, one of the founders of the 
learning league, founder of the Hawaii collegiate tournament, a member 
of the organizing committees for the Bok Choy Hat Draw, Kaimana 
Klassik, and Hopu Ka Lewa, and most recently, director of Hopu Ka Lewa.

<p><i><a href="#top">back to top</a></i>
<!--#include file="../include/blurb_border_bottom.inc"-->
