
<h1>Bidding is CLOSED. Team bids have already been processed. Contact your captain for further questions. If you submitted a bid and have not heard yet, please contact us.</h1>
<ol>

<BR><BR><BR>
 
<h4>Team Important Dates</h4>
    <li>Sept. 1, 2010 Postmark date for all team bids $309.00
    <li>Sept. 8, 2010 Accepted, wait-listed, and declined teams will be notified
    <li>Oct. 1, 2010 Last day for early-bird fee (postmarked by this date)
    <li>Oct. 1, 2010 Full refund of team Deposit (minus $5 processing fee) 
    <li>Oct. 20, 2010 Refund of team Deposit (minus one player's fee and $5 processing fee)
    <li>Oct. 20, 2010 Teams must accept/decline bids
    <li>Oct. 31, 2010 Last day to register online for regular fee (TBD).  Checks MUST be postmarked by Nov. 3rd or a late fee will be charged when you register at the fields.
    <li>November 3 - Day of Event, late fee (TBD) applies (do not mail anything nor register or pay on line, register and pay AT FIELDS day of).
</ol>
<BR><BR><BR>

<center>
<iframe src="https://spreadsheets.google.com/embeddedform?formkey=dEdMVkdOTGk2RjZOUDRGZFlCVlQwTHc6MQ" width="700" height="700" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</center>

