
<h1>Captain Instructions for Team Bid</h1>
<ol>
<h4>Complete the Bid form below or mail your own, but must include:</h4>
    <li>Contact information for captain or organizer, including name, email address, and phone number(s)
    <li>The number of players you anticipate having on your roster come November.
    <li>Approximately, what percentage of your team plan to compete in the USA Ultimate Series at the regionals or nationals level (for seeding of teams we're not familiar with)
    <li>$309 deposit (3 player fees); U.S. dollars, payable to Hopu Ka Lewa and the names of the 3 players that are covered by the bid.  Sorry, online payment is not available for team bid.
 <BR><BR>
<B>
Send all bids (if not done online) and checks to<BR>
Hopu Ka Lewa/Megan Grimshaw<BR>
3518 McCorriston St<BR>
Honolulu, HI 96815<BR>
<BR>
or email hopu2010@hawaiiultimate.com</B>
<BR><BR><BR>
 
<h4>Team Important Dates</h4>
    <li>Sept. 1, 2010 Postmark date for all team bids $309.00
    <li>Sept. 8, 2010 Accepted, wait-listed, and declined teams will be notified
    <li>Oct. 1, 2010 Last day for early-bird fee (postmarked by this date)
    <li>Oct. 1, 2010 Full refund of team Deposit (minus $5 processing fee) 
    <li>Oct. 20, 2010 Refund of team Deposit (minus one player's fee and $5 processing fee)
    <li>Oct. 20, 2010 Teams must accept/decline bids
    <li>Oct. 31, 2010 Last day to register online for regular fee (TBD).  Checks MUST be postmarked by Nov. 3rd or a late fee will be charged when you register at the fields.
    <li>November 3 - Day of Event, late fee (TBD) applies (do not mail anything nor register or pay on line, register and pay AT FIELDS day of).
</ol>
<BR><BR><BR>

<center>
<iframe src="https://spreadsheets.google.com/embeddedform?formkey=dEdMVkdOTGk2RjZOUDRGZFlCVlQwTHc6MQ" width="700" height="700" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</center>

