 <div id=hopu_menubar>
  <div id=hopu_menu>
    <ul>
      <li><a href="/hopu/">Hopu Main</a></li>
      <li><a href="/hopu/bid_hopu.asp">Team Bid</a></li>
      <li><a href="/hopu/register_hopu.asp">Ind. Registration</a><li>
      <li><a href="/hopu/logistics.shtml">Logistics</a></li>
      <li><a href="/hopu/hatdraw.shtml">Hopu Hat Draw</a></li>
      <li><a href="/hopu/history.shtml">History</a></li>
      <li><a href="http://groups.google.com/group/hopukalewa" target="blank">GoogleGroup</a></li>
    </ul>
  </div>
 </div>
