  <div id=hopu_footer>

   <center>
   <p class="announce">Hopu Ka Lewa is sponsored by <a href="http://www.hawaiiultimate.com">HULA</a>, Hawaii Ultimate League Association.<br>

Questions? Email

<script language="JavaScript">
<!--     
  var username = "hopu2010"; var domain = "hawaiiultimate.com";
  document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
  document.write (username + '@' + domain + '</a>');
//--> 
</script>
<noscript><b>hopu2010<img src=/images/at.gif>hawaiiultimate.com</b>
</noscript>
</p>

<br><br>
  </center>

  </div>
