
<h1>Individual Registration</h1>
<h2>Online Registration Is Now Open! (form below, online credit card payment after registration)</h2>

<ol>
Early Bird Player fee is $103.00 per player* this year. Fee includes all breakfasts and dinners, entertainment, camping, players' pack (disc, and HOPU surprise), plus all field supplies (water, fruit, juice, EMT). If possible, all players should register through the online registration system, which will be up and running once team bids are accepted (September 8th). If you cannot register online, please do so by sending a check payable to Hopu Ka Lewa  and mailed to Megan Grimshaw, 3518 McCorriston St, Honolulu, HI 96815. Along with your check, include your team name, the name you registered under, and meal preference. If paying by check you will still need to fill out the registration form online (just note that you paid by check).
 <BR><BR>
After October 1, 2010, registration fees will be raised to $125(you must have registered and PAID before October 1 in order to avoid the late fee). Only players registering before October 1 are guaranteed a complete players' pack.  A full player's fee refund (minus professing fee of $5) is available to players who notify the tournament director (via writing or email) before October 31th, 2010 that they will not be attending the tournament. After October 31st, players withdrawing from the tournament will receive a partial refund.
 <BR><BR>
Guest fee is $20/day (no player's pack) or $60/weekend (includes player's pack) per guest. Guest fee includes breakfasts & dinners, and entertainment. Guests may register online or by sending a check payable to Hopu Ka Lewa and mailed to Megan Grimshaw, 3518 McCorriston St, Honolulu, HI 96815.
 <BR><BR>
<B>Registration is only complete after payment is received.</B>
<BR>
<B>Please read the <a href="/hopu/waiver.html" target="blank">waiver</a> before proceeding.</B>

<h4>Individual Important Dates</h4>

    <li>October 1, 2010 Postmark for Early Bird Registration Fee $103.00
    <li>October 1-31, 2010 Regular Fee $125
    <li>October 23, 2010 Individual Refund (minus $5 processing fee)
    <li>October 31, 2010 Deadline for regular registration fee. Late fee of $142 begins
    <li>October 31, 2010 Last day to register online (payment by check must be postmarked by Nov. 3)
    <li>November 1 - Day of Event, late fee of $142 applies (do not mail or pay on line, register AT FIELDS day of)
</OL>


<BR><BR><BR><BR>
<center>
<iframe src="https://spreadsheets.google.com/embeddedform?formkey=dDVUY05UUV9hcEJEZmZTMG41MUFPUUE6MQ" width="760" height="760" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</center>
<BR><BR><BR><BR>