  <div id=hula_menu>
<ul id="MenuBar1" class="MenuBarHorizontal">
  <li><a class="MenuBarItemSubmenu" href="/play/">Play</a>
      <ul>
        <li><a href="/wiki/index.php?title=Leagues">Ultimate Leagues</a></li>
        <li><a href="/wiki/index.php?title=Tournaments">Tournaments</a></li>
        <li><a href="/wiki/index.php?title=Teams">Teams</a></li>
        <li><a href="/wiki/index.php?title=Pickup">Pickup Games</a></li>
        <li><a href="/wiki/index.php?title=Goaltimate">Goaltimate</a></li>
        <li><a href="/wiki/index.php?title=DiscGolf">Disc Golf</a></li>
      </ul>
  </li>
  <li><a class="MenuBarItemSubmenu" href="/resources/">Resources</a>
      <ul>
        <li><a href="/wiki/index.php?title=HULADocuments">Commish Handbook</a></li>
        <li><a href="/wiki/index.php?title=Maps">Maps</a></li>
        <li><a href="/wiki/index.php?title=Rules">Rules</a></li>
        <li><a href="/wiki/index.php?title=Merchandise">Merchandise</a></li>
        <li><a href="/wiki/index.php?title=HealthLinks">Health Links</a></li>
        <li><a href="/wiki/index.php?title=OtherSites">Other Sites</a></li>
      </ul>
  </li>
  <li><a class="MenuBarItemSubmenu" href="/community/">Community</a>
      <ul>
        <li><a href="/wiki/index.php?title=Special:AWCforum">Wiki Forum</a></li>
        <!--deleted bulletin board, replaced by wiki forum
        <li><a href="/forums">Bulletin Board</a></li>
        -->
	<li><a href="/wiki/index.php?title=Calendar">Calendar</a></li>
        <li><a href="/community/contacts.shtml">Contact List</a></li>
        <li><a href="/wiki/index.php?title=PhotosAndVideos">Photos and Videos</a></li>
        <li><a href="/wiki/index.php?title=Volunteer">Volunteer</a></li>
        <li><a href="/wiki">Wiki</a></li>
      </ul>
  </li>
  <li><a class="MenuBarItemSubmenu" href="/about/">About HULA</a>
      <ul>
        <li><a href="/wiki/index.php?title=HULAHistory">HULA History</a></li>
        <li><a href="/wiki/index.php?title=HULABoard">Board of Directors</a></li>
        <li><a href="/wiki/index.php?title=HULABoardMeetings">Meeting Minutes</a></li> 
        <li><a href="/about/hula_bylaws.shtml">HULA Bylaws</a></li>
        <li><a href="/about/aloha_grants.shtml">Aloha Grants</a></li>
        <li><a href="/about/hulaships.shtml">HULAships</a></li>
        <li><a href="/wiki/index.php?title=AskHULA">Ask HULA</a></li>
      </ul>
  </li>
</ul>
<script type="text/javascript">
<!--
var MenuBar1 = new Spry.Widget.MenuBar("MenuBar1", {imgDown:"/include/SpryAssets/SpryMenuBarDownHover.gif", imgRight:"/include/SpryAssets/SpryMenuBarRightHover.gif"});
//-->
</script>
</div>
