<script type="text/javascript" src="/js/hula_wiki_username.js"></script>

<div id=hula_user>
       <script language="Javascript">
       <!--
         var username = read_hula_user_cookie();
         var wiki_id = read_hula_wiki_id_cookie();
         if ((wiki_id==null||wiki_id=="") || (username==null||username=="")) {
           document.write('Hello.');
           document.write(' <a href=\"/wiki/index.php?title=Special:Userlogin\"> Sign In</a>');
           document.write(' to personalize this site.');
         } else {
           document.write('Hello ' + username + '.');
           document.write(' (if you are not ' + username + ',');
           document.write(' <a href=\"/wiki/index.php?title=Special:Userlogout\"> click here </a>.)');
         }
       //-->
       </script>
</div>
