  <div id=hula_footer></div>
  <div id=hula_bottom>
    &copy; 2007 Hawaii Ultimate League Association &nbsp; | &nbsp; 
    <script language="JavaScript">
    <!--
      var username = "webmaster";
      var domain = "hawaiiultimate.com";
      document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
      document.write (username + '@' + domain + '</a>');
    //-->
    </script>
    <noscript>
      <b>webmaster<img src=/images/at.gif>hawaiiultimate.com</b> 
    </noscript>
  </div>
