<form method="post" action="raucous_mailer.asp">
<table border=0 width="100%">
<tr><td><center><b></b>
</center>
<p align="justify">Register for Raucous Caucus by filling out the form below. Everyone is welcome to play, and if you do not have a team already, the Junta will place you on a team.</p>
<ul>
<li>Before August 10 = player fee is $10 payable to Hawaii Ultimate League Association</li>
<li>After August 10 = player fee is $15 payable to Hawaii Ultimate League Association</li>
<li>Player fees cover some of the cost of 2 breakfasts and one dinner + beverages</li>
</td></tr>

<tr><td><center>
 <table border=0><tr><td colspan="3"><hr></td></tr>
<tr><td>First Name:</td>  <td>&nbsp;&nbsp;</td>
 <td><input name="firstname" type="text"></td></tr>
<tr><td>Last Name:</td>  <td></td>
 <td><input name="lastname" type="text"></td></tr>
 </td></tr><tr><td>Email:</td>
 <td></td> <td><input name="email" type="text">&nbsp;(For confirmation.)</td></tr>
</td></tr><tr><td>Team:</td>
<td></td> <td><input name="team" type="text"> </td></tr>
 <tr><td>Gender</td> <td></td>
 <td><input name="gender" type="radio" value="Guy"> Guy&nbsp;&nbsp;     <input name="gender" type="radio" value="Gal"> Gal</td></tr>
<tr><td>Island</td> <td></td>
 <td><input name="island" type="radio" value="Oahu"> Oahu&nbsp;&nbsp;     <input name="island" type="radio" value="Maui"> Maui <input name="island" type="radio" value="BigIsland"> Big Island <input name="island" type="radio" value="Kauai"> Kauai</td></tr>

</td></tr><tr><td>Attend Saturday games?</td>
<td></td><td><input name="saturday" type="radio" value="yes"> Yes&nbsp;&nbsp;  <input name="saturday" type="radio" value="no"> No&nbsp;&nbsp;   </td></tr>

</td></tr><tr><td>Attend the Saturday dinner/party?</td>
<td></td> <td><input name="party" type="radio" value="yes"> Yes&nbsp;&nbsp; <input name="party" type="radio" value="no"> No&nbsp;&nbsp;   </td></tr>
</td></tr><tr><td>Attend Sunday games?</td>
<td></td> <td><input name="sunday" type="radio" value="yes"> Yes&nbsp;&nbsp; <input name="sunday" type="radio" value="no"> No&nbsp;&nbsp;   </td></tr>
 
 </td></tr><tr><td>Do you need a place to stay?</td>
<td></td> <td><input name="stay" type="radio" value="yes"> Yes&nbsp;&nbsp; <input name="stay" type="radio" value="no"> No&nbsp;&nbsp;   </td></tr>

 </td></tr><tr><td>Can you offer housing to someone?</td>
<td></td> <td><input name="housing" type="radio" value="yes"> Yes&nbsp;&nbsp; <input name="housing" type="radio" value="no"> No&nbsp;&nbsp;   </td></tr>

<tr><td colspan="3"><hr></td></tr>

 <tr><td colspan="3"><strong>Comments or Special Requests:</strong><br><br>If you are an interisland player requesting a play to stay or if you do not have a team, but you're requesting to be on the same team as another player, please let us know here.</center><td></tr>
<tr><td colspan="3"><center><textarea name="comments" rows="3" cols="60"></textarea></center></td></tr>

<tr><td colspan="3"><br><center><input type="submit" value="Submit Registration"></center></td></tr>

<br>
<tr><td colspan="3"><hr></td></tr>
<tr><td colspan="3">To complete your registration, you must mail a $10 check payable to 'Hawaii Ultimate League Association' to</td></tr>
<tr><td><strong><br>Laura Davis<br>RE: Raucous Caucus<br>1839 Poki St.; Apt. 8<br>Honolulu, HI 96822<br></strong></td><td></td>
</table></center></td></tr>
</table>
</form>

