
<h3>Captain Instructions</h3>
<ol>
<li> Complete letter of introduction and team roster in form below. 
<li> Print the completed form to mail in if paying by check.
<li> Pay by Credit Card or Mail $297 team deposit (payable to "Hawaii Coed Ultimate") to:<br>
Hopu Ka Lewa
c/o Megan Grimshaw
3518 McCorriston St
Honolulu HI 968
<li>Remind your teammates to complete individual registration. 
</ol>

<h3> Team Registration Form </h3>


  <form method="post" action="bidmailer_hopu.asp">

  <table border=0 width="100%">
  <tr><td><center>
   <table border=0>
    <tr><td colspan=3 height="16">
       <center>
         <font color=brown size=+2>Kamp Ka Lewa Team Bid Form</font><br><hr>
       </center>
   </td></tr>

    <tr><td width="35%" align=right valign=top><b>Team Name<sup>*</sup>:</b>
        <br> (pseudonyms, pen names, or aliases accepted) </td>
      <td width="5%"">&nbsp;&nbsp;</td> 
      <td width="60%"> <input name ="TeamName" type="text" size="30">
    </td></tr>

    <tr><td colspan=3>&nbsp;</td></tr>
 
    <tr><td align=right valign=top><b>Email<sup>*</sup>:</b>
        <br>(a real one that we can send a confirmation letter to)</td>
      <td height="22"></td> 
      <td height="22"> <input name="TeamEmail" type="text" size="20">
    </td></tr>

    <tr><td align=right valign=top><b>Letter of Introduction<sup>*</sup>:</b>
        <br> We strongly encourage creativity. Tell us how your team contributes to competitive play yet still maintains outstanding spirit.  Please limit your creative energies to space provided (press enter to advance between lines)
      </td>
      <td></td> 
      <td> <textarea name="TeamLetter" rows="30" cols="45"></textarea>
    </td></tr>

    <tr><td colspan=3 align=left><hr></td></tr>
    <tr><td colspan=3 align=left> <h3>Team Roster</h3> </td></tr>

    <tr><td colspan=3 align=left> Keep it organized folks! We try to always play 4m/3w, please be prepared. The better idea you have of who is playing on your team, the better tournament we can organize. 
</td></tr>

    <tr><td align=right valign=top><b>(Co-)Captain:</b></td>
      <td></td> 
      <td> <input type="text" name="Player1" value="">
    </td></tr>

    <tr><td align=right valign=top><b>(Co-)Captain:</b></td>
      <td></td> 
      <td> <input type="text" name="Player2" value="">
    </td></tr>

    <tr>
    <tr><td align=right valign=top><b>Players:</b></td>
      <td></td> 
      <td> <input type="text" name="Player3" value="">
           <input type="text" name="Player4" value="">
    </td></tr>

    <tr>
      <td colspan=2></td> 
      <td> <input type="text" name="Player5" value="">
           <input type="text" name="Player6" value="">
    </td></tr>

    <tr>
      <td colspan=2></td> 
      <td> <input type="text" name="Player7" value="">
           <input type="text" name="Player8" value="">
    </td></tr>

    <tr>
      <td colspan=2></td> 
      <td> <input type="text" name="Player9" value="">
           <input type="text" name="Player10" value="">
    </td></tr>

    <tr>
      <td colspan=2></td> 
      <td> <input type="text" name="Player11" value="">
           <input type="text" name="Player12" value="">
    </td></tr>

    <tr>
      <td colspan=2></td> 
      <td> <input type="text" name="Player13" value="">
           <input type="text" name="Player14" value="">
    </td></tr>

    <tr>
      <td colspan=2></td> 
      <td> <input type="text" name="Player15" value="">
           <input type="text" name="Player16" value="">
    </td></tr>

    <tr>
      <td colspan=2></td> 
      <td> <input type="text" name="Player17" value="">
           <input type="text" name="Player18" value="">
    </td></tr>

    <tr>
      <td colspan=2></td> 
      <td> <input type="text" name="Player19" value="">
           <input type="text" name="Player20" value="">
    </td></tr>


    <tr><td colspan=3 height="61"><br><hr><br><center><b>Payment</b></center></td></tr>
<tr><td height="22">Payment Fee<sup>*</sup></td> <td height="22"></td> 
  <td height="22">
	<select name=feepay>
	 <option value="blank">
	 <option value="297">Team Bid (includes 3 individual registration fees): $297
	 </select>
    </td></tr>

    <tr valign=top><td height="90"><br><input name="Payment" type="radio" value="Check"> Pay by Check</td> 
      <td height="90"></td>
	<td valign=top height="90"><br>Please send your check (payable to "Hawaii Coed Ultimate") to
		<dd>Hopu Ka Lewa<dt>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
    c/o Megan Grimshaw</dt>
		<dd>3518 McCorriston St<dd>Honolulu, HI 96815</td></tr>
<td valign=top height="15"></td></tr>


    <tr><td height="1"></td></tr>
    <tr><td colspan=3 height="20">
	<p><input name="Payment" type="radio" value="CreditCard"> Pay by Credit Card&nbsp;&nbsp;
    </td></tr>



    <tr><td colspan="3" height="72"><br><hr><br><center>
      <input type="submit" value="Submit Registration and Continue to Payment"></center></td></tr>

  </table></center></td></tr>

  </table>
</form>

