
<h1>Captain Instructions for Team Bid</h1>
<ol>
<h4>Complete the Bid form below or mail your own, but must include:</h4>
    <li>Contact information for captain or organizer, including name, email address, and phone number(s)
    <li>The number of players you anticipate having on your roster come November, as well as the number you have that are currently committed
    <li>$309 deposit (3 player fees); U.S. dollars, payable to Hopu Ka Lewa and the names of the 3 players that are coverd by the bid.  Sorry, online payment is not available for team bid.
 <BR><BR>
<B>
Send all bids (if not done online) and checks to<BR>
Hopu Ka Lewa/Megan Grimshaw<BR>
3518 McCorriston St<BR>
Honolulu, HI 96815<BR>
<BR>
or email hopu@hawaiiultimate.com</B>
<BR><BR><BR>
 
<h4>Team Important Dates</h4>
    <li>September 1, 2009 Postmark date for all team bids $309.00
    <li>September 15, 2009 Accepted, wait-listed, and declined teams will be notified
    <li>September 31, 2009 Full refund of team Deposit (minus $5 processing fee) 
    <li>October 1-23, 2009 Refund of team Deposit (minus one player's fee and $5 processing fee)
    <li>October 23, 2009 Teams must accept/decline bids
    <li>October 24, 2009 No refunds of team deposits upon forfeiture after this date
    <li>October 31, 2009 Deadline for regular registration fee. Late fee begins, $130.
    <li>Ocotber 31, 2009 Last day to register online.
    <li>October 31, 2009 last day to recieve checks, must be post marked by October 29th.
    <li>November 1 - Day of Event, Registration Fee $130.00 (do not mail or pay on line, register AT FIELDS day of) 
</ol>
<BR><BR><BR>

<center>
<iframe src="http://spreadsheets.google.com/embeddedform?key=0AlAlSxG6h_ocdG5ydVV4a05JekswTjNFUUhiTU9KM3c" width="740" height="1000" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</center>

