
  <form method="post" action="regmailer_hopu.asp">

  <table border=0 width="100%">
  <tr><td><center>
   <table border=0>
    <tr><td colspan=3 height="16">
       <center>
         <font color=brown size=+2>Online registration and payment is now closed. 
Please register and pay at Waimanalo Polo Fields Friday evening between 6 pm and 9 pm. Field is on the mountain side of Kalanianaole Highway across from Bellows Beach.
</font><br><hr>
       </center>
   </td></tr>


  </table></center></td></tr>

  </table>
</form>

