 <div id=hopu_menubar>
  <div id=hopu_menu>
    <ul>
      <li><a href="/hopu/">Hopu Main</a></li>
      <li><a href="/hopu/registration.shtml">Registration</a></li>
      <li><a href="/hopu/bidprocess.shtml">Bids & Fees</a></li>
      <li><a href="/hopu/logistics.shtml">Logistics</a></li>
      <li><a href="/hopu/hatdraw.shtml">Post-Hopu Hat Draw</a></li>
<!--
      <li><a href="/hopu/directions.shtml">Directions</a></li>
-->
      <li><a href="/hopu/history.shtml">History</a></li>
    </ul>
  </div>
 </div>
