<form method="post" action="regmailer_league.asp">
<table border=0 width="100%">
<tr><td><center><b>Welcome to the 2008 Spring League Season!</b>
</center>
<p align="justify"><font color="#ff0000">

Questions? Please email <b>

<script language="JavaScript">
<!--
      var username = "spring2008";
 var domain = "hawaiiultimate.com";
 document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
 document.write (username + '@' + domain + '</a>');
//-->
</script>
<noscript><b>spring2008<img src=/at.gif>hawaiiultimate.com</b>
</noscript>

for more information.</b>

</font>

<p align="justify">Please fill out the fields below to register for the league draft.  Please note that starred (<sup>*</sup>) items are <b>required</b>.</p>

<p align="justify">You should receive a confirmation email following the completion and submission of your registration.  <b>If you do not receive this email</b>, please ensure that your email address is spelled correctly and resubmit your registration with your corrected address if needed.  If you still do not receive a confirmation email, please contact <b>

<script language="JavaScript">
<!--
      var username = "webmaster";
 var domain = "hawaiiultimate.com";
 document.write ('<a href=\"mailto:' + username + '@' + domain + '\">');
 document.write (username + '@' + domain + '</a>');
//-->
</script>
<noscript><b>webmaster<img src=/at.gif>hawaiiultimate.com</b>
</noscript>

</b> for further assistance.</p>

<p><i>[Note: Spouses or significant others may request to be placed on the same team but must explain why in the comments field below. Beginners to the game may also request to be placed on the same team with a particular returning player (i.e. the individual responsible for recruiting the new player) or fellow beginner. Such requests should be indicated in the comments section below and will be accomodated as possible.]</i></p>
</td></tr>

<tr><td><center>
 <table border=0><tr><td colspan=3><hr></td></tr>
<tr><td>First Name<sup>*</sup></td>  <td>&nbsp;&nbsp;</td>
 <td><input name ="firstname" type="text"></td></tr>
<tr><td>Last Name<sup>*</sup></td>  <td></td>
 <td><input name="lastname" type="text">
 </td></tr>
<tr><td>Nickname (if any)</td>
 <td></td> <td><input name="nickname" type="text">
 </td></tr><tr><td>Email<sup>*</sup></td>
 <td></td> <td><input name="email" type="text"> (NOTE: this email address will be subscribed to our <a href="http://sports.groups.yahoo.com/group/hulamail/">hulamail</a> yahoo email group)</td></tr>
<tr><td>Phone Number<sup>*</sup></td>
 <td></td><td><input name="phone" type="text"></td></tr>
<tr><td>Birthday (year optional)</td> <td></td> <td><input name="birthday" type="text"></td></tr>
<tr><td>Sex<sup>*</sup</td> <td></td>
 <td><input name="gender" type="radio" value="Male"> Male&nbsp;&nbsp;     <input name="gender" type="radio" value="Female"> Female</td></tr>
<tr><td colspan="3"><br>How often do you check email?<br>
 <input name="freq" type="radio" value="daily">Daily&nbsp;&nbsp;
 <input name="freq" type="radio" value="weekly">A few times weekly&nbsp;&nbsp;
 <input name="freq" type="radio" value="never">Almost never. Please call.</td></tr>
<tr><td colspan="3"><br>Height<br> Males:
 <input name="height" type="radio" value="short_male">5'6"&nbsp;and&nbsp;under&nbsp;&nbsp;
 <input name="height" type="radio" value="average_male">5'7"&nbsp;-&nbsp;6'0"&nbsp;&nbsp;
 <input name="height" type="radio" value="tall_male">6'1"&nbsp;and&nbsp;up
  <br> Females:
 <input name="height" type="radio" value="short_female">5'3"&nbsp;and&nbsp;under&nbsp;&nbsp;
 <input name="height" type="radio" value="average_female">5'4"&nbsp;-&nbsp;5'8"&nbsp;&nbsp;
 <input name="height" type="radio" value="tall_female">5'9"&nbsp;and&nbsp;up</td></tr>
<tr><td colspan="3"><br>Commitment Level:  How many games do you expect to attend?<br>
 <input name="commitment" type="radio" value="10%">10%&nbsp;&nbsp;
 <input name="commitment" type="radio" value="20%">20%&nbsp;&nbsp;
 <input name="commitment" type="radio" value="30%">30%&nbsp;&nbsp;
 <input name="commitment" type="radio" value="40%">40%&nbsp;&nbsp;
 <input name="commitment" type="radio" value="50%">50%&nbsp;&nbsp;<br>
 <input name="commitment" type="radio" value="60%">60%&nbsp;&nbsp; <input name="commitment" type="radio" value="70%">70%&nbsp;&nbsp;
 <input name="commitment" type="radio" value="80%">80%&nbsp;&nbsp;
 <input name="commitment" type="radio" value="90%">90%&nbsp;&nbsp;
 <input name="commitment" type="radio" value="100%">100%<br>


 <i>Please be realistic. Account for games you will miss due to travel, friends and family in town, prior commitments, etc.




<tr><td colspan="3"><br>Preferred Playing Position<br>
 <input name="position" type="radio" value="Handler">Handler&nbsp;&nbsp;
 <input name="position" type="radio" value="Middle">Middle&nbsp;&nbsp; <input name="position" type="radio" value="Deep">Deep&nbsp;&nbsp;<br>
 <input name="position" type="radio" value="Don't Know / Don't Care">Don't&nbsp;Know&nbsp;/&nbsp;Don't&nbsp;Care</td></tr>

<tr><td colspan="3"><br>Leadership<br>
 <input name="leadership" type="radio" value="No">Don't make me a captain<br>
 <input name="leadership" type="radio" value="Maybe">Wouldn't mind being a captain<br>
 <input name="leadership" type="radio" value="Yes">Excited to be a captain (yes, I am volunteering!)</td></tr>
<tr><td colspan="3"><br><hr><br>Experience<br><table border=0>
	<tr><td><input name="experience" type="radio" value="1"></td><td>[1] Never played before</td>
	<tr><td><input name="experience" type="radio" value="2"></td><td>[2] Played some pickup or rec night</td>
	<tr><td><input name="experience" type="radio" value="3"></td><td>[3] Played one season of city league</td>
	<tr><td><input name="experience" type="radio" value="4"></td><td>[4] Played 2 to 4 seasons of league</td>
	<tr><td><input name="experience" type="radio" value="5"></td><td>[5] Played 5+ seasons of league or in Hopu</td>
	<tr><td><input name="experience" type="radio" value="6"></td><td>[6] Played in Kaimana once or Hopu multiple times</td>
	<tr><td><input name="experience" type="radio" value="7"></td><td>[7] Played in Club Regionals, or in Club Sectionals or Kaimana multiple times</td>
	<tr><td><input name="experience" type="radio" value="8"></td><td>[8] Retired Club Nationals or Regionals player or played in Kaimana 5+ times</td>
	<tr><td><input name="experience" type="radio" value="9"></td><td>[9] Played in College or Club Nationals</td>
	<tr><td><input name="experience" type="radio" value="10"></td><td>[10] Played in Club Nationals on an elite team or multiple times</td>
	</table>
    </td></tr>

    <tr><td colspan="3"><br>Skills<br>
	<input name="skills" type="radio" value="1">[1] Just learning to throw<br>
	<input name="skills" type="radio" value="2">[2] Decent backhand or forehand<br>
	<input name="skills" type="radio" value="3">[3] Familiar with stack offense (and #2)<br>
	<input name="skills" type="radio" value="4">[4] Familiar with zone offense (and #2)<br>
	<input name="skills" type="radio" value="5">[5] Solid backhand and forehand<br>
	<input name="skills" type="radio" value="6">[6] Occasional break mark throws<br>
	<input name="skills" type="radio" value="7">[7] Strong backhand and forehand<br>
	<input name="skills" type="radio" value="8">[8] Strong handler (both stack and zone offense)<br>
	<input name="skills" type="radio" value="9">[9] Accurate backhand and forehand hucks<br>
	<input name="skills" type="radio" value="10">[10] Accurate break mark throws and hucks<br>
    </td></tr>

    <tr><td colspan="3"><br>Speed<br>
	<input name="speed" type="radio" value="1">[1] Little on the slow side<br>
	<input name="speed" type="radio" value="2">[2] Average<br>
	<input name="speed" type="radio" value="3">[3] Good<br>
	<input name="speed" type="radio" value="4">[4] Pretty fast<br>
	<input name="speed" type="radio" value="5">[5] One of the fastest on the field
    </td></tr>

    <tr><td colspan="3"><br>Athleticism<br>
	<input name="athleticism" type="radio" value="1">[1] Can't run or jump, but love to play!<br>
	<input name="athleticism" type="radio" value="2">[2] Average<br>
	<input name="athleticism" type="radio" value="3">[3] Good<br>
	<input name="athleticism" type="radio" value="4">[4] Very Good<br>
	<input name="athleticism" type="radio" value="5">[5] Outstanding<br>
    </td></tr>

    <tr><td colspan="3"><br>Spirit: From the UPA's On Spirit of the Game: "Highly
		competitive play is encouraged, but never at the expense of the bond
		of mutual respect between players, adherence to the agreed-upon rules
		of the game, or the basic joy of play."<br>
	<table border=0>
	<tr><td><input name="spirit" type="radio" value="1"></td><td>[1] Spirit ain't my thing<br>
	<tr><td><input name="spirit" type="radio" value="2"></td><td>[2] I try a little, but usually the devil
							gets the best of me</td></tr>
	<tr><td><input name="spirit" type="radio" value="3"></td><td>[3] I try to be a 5 but sometimes the devil
							gets the best of me</td></tr>

<tr><td>
 <input name="spirit" type="radio" value="4"></td>
 <td>[4] I make my best effort and I'm usually able to meet most or all of the criteria to be a 5 in spirit</td></tr>
<tr><td><input name="spirit" type="radio" value="5"></td>
 <td>[5] I am respectful of all players at all times, I know the 11th edition rules, I play fairly, I make fair calls, and I play with safety of myself and others as a top priority</td></tr></table> </td></tr>


<tr><td colspan="3"><br>
<hr><br>Comments or Special Requests<br>
<textarea name="comments" rows="2" cols="30"></textarea><br><i>If you are requesting to be on the same team as a spouse, significant
	other, or (if a beginner) any other fellow player, please justify your request here.</i>   </td></tr> <tr><td colspan="3"><br><hr><br><center><input type="submit" value="Submit Registration"></center>
</td></tr>
</table></center></td></tr>
</table>
</form>

