<iframe src="http://spreadsheets.google.com/embeddedform?key=pM86KqFxbSYUid4PPHpgAUA" width="310" height="3386" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

           <!-- Start Mailing Lists -->
		<b>Other Stuff:</b>
		Want to sign up for one
		or all of HULA's email lists?  Click below for more information or to subscribe.
		<br>&nbsp;&#149;&nbsp;<b><a href="http://groups.yahoo.com/group/hulamail" target="maillist">hulamail</a></b> - official disc-related announcements
		<br>&nbsp;&#149;&nbsp;<b><a href="http://groups.yahoo.com/group/hula_generalmail" target="maillist">generalmail</a></b> - community announcements
		<br>&nbsp;&#149;&nbsp;<b><a href="http://groups.yahoo.com/group/hula_wahinemail" target="maillist">wahinemail</a></b> - women's events/discussion

		<hr width="50%" align=center>
		Also, want to buy a HULA disc or three?  Contact <a href="mailto:mchun@hawaiiultimate.com">mchun@hawaiiultimate.com</a> for information.
           <!-- End Mailing Lists -->

		<center><i>Back to the <a href="league.asp">league home page</a>.</i></center>


  <script language="LiveScript">
  <!---//hide script from old browsers
      document.write( "<font size=2><i>Last updated "+ document.lastModified +"</i></f
ont>");
  //end hiding contents ---> </script>

