            <table width="442" border="0" cellspacing="0" cellpadding="0" bgcolor="#cccccc" align="left" valign="top">
               <tr>  
                  <td width="30" align="left" valign="top" bgcolor="#cccccc">
                     <img src="images/blank.gif" width="30" height="20" alt=" ">
                  </td>

                  <td width="410" align="left" valign="top" bgcolor="#cccccc">
                    <center><p>
                     <a class="topnav" href="index.shtml">Home</a>
                     |
                     <a class="topnav" href="details.shtml">Tourney Details</a>
                     |
                     <a class="topnav" href="bidproc.shtml">Bid Process &amp; Fees </a> 
                     |
                     <a class="topnav" href="history.shtml">History</a>
                     <br>
                     <a class="topnav" href="hatdraw.shtml">Pre-Hopu Hat Draw</a>
                     |
                     <a class="topnav" href="reg_team.shtml">Team Registration</a>
                     |
                     <a class="topnav" href="register_hopu.asp">Individual Registration</a>
                     <br>
                    </p></center>
                  </td>


                  <td width="2" align="left" valign="top" bgcolor="#cccccc">
                     <img src="images/blank.gif" width="2" height="20" alt=" ">
                  </td>
               </tr>
            </table>

