<html> 
<head><title>ASP Mailer</title></head> 
<body> 
<H3>ASP Mailer</H3> 

<%@ LANGUAGE = JScript %> 

<% 
Request.Form("aspmail.asp")
var Mailer = Server.CreateObject("SMTPsvg.Mailer");
Mailer.FromName = "Nexpoint Support";
Mailer.FromAddress = "webmaster@hawaiiultimate.com";
Mailer.RemoteHost = "hawaiiultimate.com";
Mailer.AddRecipient (Request.Form("name"), Request.Form("email"));
Mailer.Subject = "Generated by aspmailer.asp";
Mailer.BodyText = "This is a test of http://www.lemonskies.com/aspmailer.asp";

if (Mailer.SendMail()) 
{ 
Response.Write("Mail successfully sent") 
} 
else 
{ 
Response.Write("Mail failure. Check mail host server name and tcp/ip connection...\n"); 
Response.Write("<br>\n");
Response.Write(Mailer.Response); 
Response.Write("<br>\n");
Response.Write(Mailer.FromName);
Response.Write("<br>\n");
Response.Write(Mailer.FromAddress);
Response.Write("<br>\n");
Response.Write(Mailer.RemoteHost);
Response.Write("<br>\n");
}

%> 

</body> 
</html>
