          <tr><td colspan="9" align="center">
            <a href="hula_about.html">intro</a> |
            <a href="hula_bylaws.html">HULA bylaws</a> |
            <a href="hula_commish.pdf" target="new">commissioner's handbook</a> |
            <a href="hula_alohagrants.html">aloha grants</a> |
            <a href="hula_hulaships.html">HULAships</a> |
            <a href="hula_board.html">board of directors</a> |
            <a href="hula_minutes.html">HULA board meetings</a>
          </td></tr>
