 <div id=hopu_menubar>
  <div id=hopu_menu>
    <ul>
      <li><a href="/hopu/">Hopu Main</a></li>
      <li><a href="/hopu/register_hopu.asp">Registration</a></li>
      <li><a href="/hopu/bid_hopu.asp">Bids & Fees</a></li>
      <li><a href="/hopu/logistics.shtml">Logistics</a></li>
      <li><a href="/hopu/hatdraw.shtml">Post-Hopu Hat Draw</a></li>
      <li><a href="/hopu/history.shtml">History</a></li>
      <li><a href="/wiki/index.php?title=Special:AWCforum&action=sf/id6">Forums</a></li>
    </ul>
  </div>
 </div>
