
<h1>Individual Registration</h1>

<ol>
Early Bird Player fee is $103.00 per player* this year. Fee includes all breakfasts and dinners, entertainment, camping, players' pack (disc, and HOPU surprise), plus all field supplies (water, fruit, juice, EMT). If possible, all players should register through the online registration system, which will be up and running once team bids are accepted (September 1st). If you cannot register online, please do so by sending a check payable to Hopu Ka Lewa  and mailed to Megan Grimshaw, 3518 McCorriston St, Honolulu, HI 96815. Along with your check, include your team name, the name you registered under, and meal preference. If paying by check you will still need to fill out the registration form online (just note that you paid by check).
 <BR><BR>
After October 1, 2009, registration fee is $115 (you must have registered and PAID before October 1 in order to avoid the late fee). Only players registering before October 1 are guaranteed a complete players' pack.  A full player's fee refund (minus professing fee of $5) is available to players who notify the tournament director (via writing or email) before October 31th, 2009 that they will not be attending the tournament. After October 31th, players withdrawing from the tournament will receive a partial refund.
 <BR><BR>
Guest fee is $20/day (no player's pack) or $60/weekend (includes player's pack) per guest. Guest fee includes breakfasts & dinners, and entertainment. Guests may register online or by sending a check payable to Hopu Ka Lewa and mailed to Megan Grimshaw, 3518 McCorriston St, Honolulu, HI 96815.
 <BR><BR>
<B>Registration is only complete after payment is received.</B>
<BR>
<B>Please read the <a href="/hopu/waiver.html" target="blank">waiver</a> before proceding.</B>

<h4>Individual Important Dates</h4>

    <li>October 1, 2009 Postmark for Early Bird Registration Fee $103.00
    <li>October 1-31, 2009 Regular Fee $115.00
    <li>October 23, 2009 Individual Refund (minus $5 processing fee)
    <li>October 31, 2009 Deadline for regular registration fee. Late fee begins, $130.
    <li>October 31, 2009 Last day to register online .
    <li>October 31, 2009 last day to recieve checks, must be post marked by October 29th.
    <li>November 1 - Day of Event, Registration Fee $130.00 (do not mail or pay on line, register AT FIELDS day of)
</OL>

<center>
<iframe src="http://spreadsheets.google.com/embeddedform?key=0AlAlSxG6h_ocdEo5ZUxneFhERkZDb3h6SHdOWFk4eHc" width="740" height="1500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</center>
<BR><BR><BR><BR>
